version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-test
    environment:
      POSTGRES_DB: Test_DB
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: Admin1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata: