version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres_test:Admin1@postgres:5432/Test_DB
      - REDIS_URL=redis://:Alpha_1997@redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
      
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres-test
    environment:
      POSTGRES_DB: Test_DB
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: Admin1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_test -d Test_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Alpha_1997", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: